- src/webpack/create-controllers-module.js
- test/webpack/create-controllers-module.test.js
webpack restrict some optimizations to ES modules, bailing out for CommonJS. So using an ES module is better.
> Generate the controllers virtual module as an ES module

- package.json
@weaverryan I'm not sure in which context I ended up without this module but I did in a project:
```
yarn dev
yarn run v1.22.5
warning ../../../package.json: No license field
$ encore dev
Running webpack ...
ERROR  Failed to compile with 1 errors                                                                                                                                                                                    10:41:04 PM
error  in ./assets/app.js
Syntax Error: Error: Cannot find module '@babel/plugin-proposal-class-properties' from '/home/tgalopin/Projects/citipo/marketing'
at Array.map (<anonymous>)
at cachedFunction.next (<anonymous>)
at Generator.next (<anonymous>)
at buildRootChain.next (<anonymous>)
at loadPrivatePartialConfig.next (<anonymous>)
at Generator.next …
```
> Add explicit dependency on @babel/plugin-proposal-class-properties

- src/index.js
- test/index.test.js
Following https://github.com/symfony/stimulus-bridge/pull/9, let's stick to something cleaner as after testing several options this is the most reliable one.
This PR introduces breaking changes for users of the bridge if they invoke manually Stimulus controller from vendors. However, I think this is necessary and the bridge isn't used too much in this situation yet. Also, this package is experimental precisely for these situations :) .
If merged, controllers coming from vendors would be normalized the same way the app controllers are: `@symfony/ux-dropzone/dropzone` would become `symfony--ux-dropzone--dropzone`. This is consistent with Stimulus way of doing this and it will allow us to better leverage the Target and Data API.
> Normalize Stimulus controller names

- CHANGELOG.md
- README.md
Hi!
I'd personally like a CHANGELOG - I rely on them a lot in the JS world, as things change a lot. And also, with the breaking change in 1.2.0, I think it would help.
Cheers!
> Adding CHANGELOG

- types/index.d.ts
Just noticed afterwards that in the meantime the type changed to be optional in #10. 
https://github.com/symfony/stimulus-bridge/blob/c29caa8a9ff4217c69c06efbb9036276507a28e0/src/index.js#L22-L24
> Fix param type

- package.json
See #11.
tl;dr we do not *actually* depend on this library, though Stimulus requires it if you're using its normal `targets =  syntax. However, *how* that currently works with Encore is a bit of a mystery.
Still, I do not believe having this as a dependency solves or does anything.  And since it's not part of any release yet, let's remove it.
> removing class-properties

- CHANGELOG.md
- README.md
- dist/index.js
- dist/webpack/create-controllers-module.js
- dist/webpack/generate-lazy-controller.js
- dist/webpack/loader.js
- src/index.js
- src/webpack/create-controllers-module.js
- src/webpack/generate-lazy-controller.js
- src/webpack/loader.js
- test/fixtures/deprecated-webpack-mode.json
- test/fixtures/disabled-autoimport.json
- test/fixtures/disabled-controller.json
- test/fixtures/eager-autoimport.json
- test/fixtures/eager-no-autoimport.json
- test/fixtures/lazy-no-autoimport.json
- test/webpack/create-controllers-module.test.js
- test/webpack/generate-lazy-controller.test.js
Hi!
This deprecates the `webpackMode` option in `controllers.json` and replaces it with a new `lazy` option that can be set to `eager` or `lazy`.
The `lazy` mode is quite a bit smarter than the old `webpackMode: 'lazy'`. When you use this, the controller (and its dependencies) isn't downloaded until the corresponding `data-controller` appears on the page. This is great for things like chartjs, which is quite huge, but probably you don't have it on every page and a tiny delay is no problem.
PR to update the UX packages: https://github.com/symfony/ux/pull/53
Cheers!
Fixes https://github.com/symfony/stimulus-bridge/issues/3
> "fetch: lazy": don't download until the controller is present

- CHANGELOG.md
- README.md
- dist/util/get-stimulus-comment-options.js
- dist/webpack/lazy-controller-loader.js
- lazy-controller-loader.js
- package.json
- src/util/get-stimulus-comment-options.js
- src/webpack/lazy-controller-loader.js
- test/util/get-stimulus-comment-options.test.js
- test/webpack/lazy-controller-loader.test.js
Hi!
This allows users to make their own controllers "lazy" by adding a special comment above their controllers:
```js
// assets/controllers/hello_controller.js
import { Controller } from 'stimulus';
/* stimulusFetch: 'lazy' */
export default class extends Controller {
// ...
}
```
When you do this, your controller (and its dependencies) are *not* included in the main `app.js` built file. Instead, they are split into their own chunk/file. This file is loaded asynchronously the moment that the *first* element appears on the page for this controller (e.g. `<div data-controller="hello">`). This follows up on #15 (and only the last commit is new to this PR). The `/* stimulusFetch: 'lazy' */` is inspired by Webpack's `/* webpackMode: 'lazy' */` comments and uses the same mechanism to parse …
> Lazy controllers for user-land controllers

- dist/webpack/create-controllers-module.js
- src/webpack/create-controllers-module.js
I hit this locally - I (duh) forgot to run `yarn install --force` after installing a UX package. I've tested this on a real project.
> Adding a hint of we can't find the package.json file

- .github/workflows/test.yaml
- CHANGELOG.md
- README.md
- dist/index.js
- dist/webpack/create-controllers-module.js
- dist/webpack/lazy-controller-loader.js
- package.json
- src/index.js
- src/webpack/create-controllers-module.js
- src/webpack/lazy-controller-loader.js
- test/fixtures/module/dist/controller.js
- test/webpack/create-controllers-module.test.js
- test/webpack/generate-lazy-controller.test.js
Adds support for Stimulus 3. Unless we get fancy (which we could I think, but it's a bit unnatural), this will require a new major release of this library.
TODOs:
Before a tag, we need to
> Supporting Stimulus 3

- dist/webpack/lazy-controller-loader.js
- dist/webpack/loader.js
- src/webpack/generate-lazy-controller.ts
- test/webpack/create-controllers-module.test.ts
- test/webpack/generate-lazy-controller.test.ts
- test/webpack/lazy-controller-loader.test.ts
One big, but kind of hidden change with Stimulus 3 is that IE11 support/ES5 has been dropped. This means, for example, that the Stimulus' classes are no longer transpiled from ES6 to ES5: they remain as true ES6 classes.
For the lazy controller, we need to do the same because you cannot extend an ES6 class with an ES5 class.  But also, since we're no longer support ES5, this just generates better code :)
> Lazy controller loader: generate true ES6 class

- README.md
Apparently encore needs different parameters than shown in the docs to run. The proposed change seems to work just fine.
Running `yarn encore watch` results in an error:
```bash
✗ yarn encore watch
yarn run v1.22.10
$ /Users/martinhauke/workspace/example/symfony/basic/app/node_modules/.bin/encore watch
Invalid command "watch"
usage encore [dev|prod|production|dev-server]
encore is a thin executable around the webpack or webpack-dev-server executables
Commands:
dev        : runs webpack for development
- Supports any webpack options (e.g. --watch)
dev-server : runs webpack-dev-server
- --host The hostname/ip address the webpack-dev-server will bind to
- --port The port the webpack-dev-server will bind to
- --keep-public-path Do not change the public path (it is usually prefixed by the dev …
```
> Fix documentation on how to run encore

- CHANGELOG.md
- dist/index.js
- src/index.ts
Hi!
Well... this was such an easy win, we should have done it awhile ago :).
For a "dev" build, this activates Stimulus's debug mode, which outputs a lot of information to the log. Here is an example of a page with a single controller... and then after I activate an action on that controller:
When running `yarn encore production` (or `npm run encore production`), debug mode will be disabled. Heck, Weback is SO cool that, when building for production, the entire new `if` statement is omitted (i.e. this adds 0 extra bytes to production builds).
> Activating "debug" mode for Stimulus for dev builds

- dist/webpack/loader.js
- src/webpack/create-controllers-module.ts
- test/fixtures/load-named-controller.json
- test/fixtures/module/package.json
- test/fixtures/override-name.json
- test/index.test.ts
- test/webpack/create-controllers-module.test.ts
This is needed for live components, where the controller name needs to be simply `live`... else it will be super annoying to use :). 
Allowing the user to also override the controller name... isn't really needed... but if the user does this, I think they know they are on their own.
This COULD actually replace #69... as a package could add, for example, `name: 'symfony/ux-typed'` to change the name to a shorter version.
> Allowing the controller name to be overridden by the package or the user

- package.json
I was not able to run tests after cloning the repository and installing dependencies, because `@babel/plugin-proposal-class-properties` is missing:
```
➜  symfony-stimulus-bridge git:(main) yarn test
! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e.
! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager
yarn run v1.22.22
$ yarn run webpack --config test/webpack.config.js && yarn run jest
$ /Users/kocal/workspace-os/symfony-stimulus-bridge/node_modules/.bin/webpack --config test/webpack.config.js
asset index.js 94.9 KiB [emitted] …
```
> Add missing `@babel/plugin-proposal-class-properties` dev dependency

- dist/webpack/lazy-controller-loader.js
- src/util/get-stimulus-comment-options.ts
- test/util/get-stimulus-comment-options.test.ts
Fixes #84 
`acorn` should be configured to use ECMAScript version 2022 instead of 2020, which does not support static class properties.
See https://github.com/symfony/stimulus-bridge/issues/84#issuecomment-2383772104 for explanation.
> Fix lazy-controller detection when controller contain static properties (update `acorn` ECMAScript version)

- .github/workflows/test.yaml
- package.json
Let's _modernize_ this repository 🙌🏻 
Starting first with CI improvments
> [BREAKING] Drop support for Node.js 10 and 12, ensure in the CI tests are run under multiple Node.js versions

- .github/workflows/test.yaml
- package.json
Following #94, let's continue to drop old unmaintained [Node.js versions](https://nodejs.org/en/about/previous-releases):
> [BREAKING] Drop Node.js 14 and 16 support

- CHANGELOG.md
- package.json
- pnpm-lock.yaml
```
Package size report
===================
Package info for "@symfony/stimulus-bridge@3.2.3": 3.1 MB
Released: 2025-01-09 07:16:42.242 +0000 UTC (2w5d ago)
Downloads last week: 12,772 (21.82%)
Estimated traffic last week: 40 GB
Subdependencies: 17
Removed dependencies:
- acorn@8.14.0: 547 kB (17.38%)
Downloads last week: 22,267,720 (N/A% from 8.14.0)
Downloads last week from "@symfony/stimulus-bridge@3.2.3": 12,772 (N/A%)
Traffic last week: N/A
Traffic from "@symfony/stimulus-bridge@3.2.3": 40 GB (N/A%)
Subdependencies: 0 (0%)
Estimated new statistics:
Package size: 3.1 MB → 2.4 MB (74.94%)
Subdependencies: 17 → 16 (-1)
Traffic with last week's downloads:
For current version: 40 GB → 30 GB (10 GB saved)
For all versions: 184 GB → 138 GB (46 GB saved)
```
A little disappointed, I thought …
> Move `acorn` dependency to devDependency, as it is already bundled in dist files, close #112

- .babelrc
- CHANGELOG.md
- babel.config.js
- package.json
- pnpm-lock.yaml
- test/webpack/generate-lazy-controller.test.ts
Babel configuration files `.babel.rc` and `babel.config.js` were not used (anymore), `@babel/parser` can be replaced by `acorn` that we already use, so we can remove Babel and remove ~120 devDependencies:
- before:
```
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 11[8](https://github.com/symfony/stimulus-bridge/actions/runs/13026638540/job/36336794852?pr=115#step:6:9), reused 1, downloaded 99, added 0
Progress: resolved 284, reused 1, downloaded 243, added 0
Packages: +360
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 423, reused 1, downloaded 364, added 360, done
.../esbuild@0.24.2/node_modules/esbuild postinstall$ node install.js
.../node_modules/@biomejs/biome postinstall$ node scripts/postinstall.js …
```
> Remove Babel (which was not really necessary), replace it by acorn if needed, close #105
